language: node_js
node_js:
 - 12.12.0
before_install:
  - npm i -g firebase-tools
  - npm install -g eslint
script:
  - npm run lint
after_success:
  - npm run deploy
notifications:
  email: false
deploy:
  provider: firebase
  token: 1//0c5XD6fx_-263CgYIARAAGAwSNwF-L9IrsNpOatjy9fthj5COVqlkHsf82YvypGWabewPkg68JmzvjOGwa4672D9bqs2q_pxZ2cA
branches:
  only:
    - master